language: node_js
node_js:
  - "0.10"
before_install:
  - npm install
  - npm install -g grunt-cli
  - npm install -g web-component-tester
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - grunt test-travis