language: node_js
node_js:
  - "0.10"
addons:
  firefox: "35.0"
before_script:
  - npm install
  - npm install -g grunt-cli
  - npm install -g web-component-tester
  - npm install -g bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 6 # give xvfb some time to start
script:
  - wct
  - grunt test-travis
